### ISSUE TITLE
Unclear error message when a type ends with a capital letter

### ISSUE THREAD

**Issue by zerovox** [palantir/conjure#432] opened 2019-11-01 18:05 UTC
## What happened?

When compiling:

```
types:
  definitions:
    default-package: com.palantir.test
    objects:
      TestA: {}

```

or any type that has two capital letters in a row you get the following error:

```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.palantir.conjure.cli.ConjureCli$CompileCommand@3abada5a): java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `com.palantir.conjure.parser.types.names.TypeName` from String "TestA": not a valid representation, problem: (java.lang.reflect.InvocationTargetException) null
 at [Source: (File); line: 5, column: 7] (through reference chain: com.palantir.conjure.parser.ImmutableConjureSourceFile$Json["types"]->com.palantir.conjure.parser.types.ImmutableTypesDefinition$Json["definitions"]->com.palantir.conjure.parser.types.ImmutableNamedTypesDefinition$Json["objects"])
        at picocli.CommandLine.execute(CommandLine.java:1051)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
        at picocli.CommandLine.run(CommandLine.java:1864)
        at picocli.CommandLine.run(CommandLine.java:1794)
        at com.palantir.conjure.cli.ConjureCli.main(ConjureCli.java:39)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `com.palantir.conjure.parser.types.names.TypeName` from String "TestA": not a valid representation, problem: (java.lang.reflect.InvocationTargetException) null
 at [Source: (File); line: 5, column: 7] (through reference chain: com.palantir.conjure.parser.ImmutableConjureSourceFile$Json["types"]->com.palantir.conjure.parser.types.ImmutableTypesDefinition$Json["definitions"]->com.palantir.conjure.parser.types.ImmutableNamedTypesDefinition$Json["objects"])
        at com.palantir.conjure.parser.ConjureParser$RecursiveParser.parseInternal(ConjureParser.java:114)
        at com.palantir.conjure.parser.ConjureParser$RecursiveParser.parse(ConjureParser.java:88)
        at com.palantir.conjure.parser.ConjureParser.parse(ConjureParser.java:60)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.palantir.conjure.defs.Conjure.parse(Conjure.java:37)
        at com.palantir.conjure.cli.ConjureCli$CompileCommand.generate(ConjureCli.java:71)
        at com.palantir.conjure.cli.ConjureCli$CompileCommand.run(ConjureCli.java:66)
        at picocli.CommandLine.execute(CommandLine.java:1043)
        ... 8 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `com.palantir.conjure.parser.types.names.TypeName` from String "TestA": not a valid representation, problem: (java.lang.reflect.InvocationTargetException) null
 at [Source: (File); line: 5, column: 7] (through reference chain: com.palantir.conjure.parser.ImmutableConjureSourceFile$Json["types"]->com.palantir.conjure.parser.types.ImmutableTypesDefinition$Json["definitions"]->com.palantir.conjure.parser.types.ImmutableNamedTypesDefinition$Json["objects"])
 ...
```

## What did you want to happen?
A clear error message (not an NPE) that explains what constitutes a "valid representation" and what didn't match. Unclear why the message from the check method isn't returned https://github.com/palantir/conjure/blob/master/conjure-core/src/main/java/com/palantir/conjure/parser/types/names/TypeName.java#L46

**Comment by nmiyake** [comment] 2019-11-01 18:07
Dupe of #72

**Closed** 2019-11-01 19:18 UTC
